name: Update wiki

permissions:
  contents: write
  
on:
  push:

jobs:
  set_wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Echos
        run: |
          echo Message : ${{ github.event.head_commit.message }}
          echo Repo actuel : ${{ github.repository }}
          echo "NOW=$(date +'%d/%m/%Y %H:%M:%S')" >> $GITHUB_ENV
          echo Date : $NOW
          echo $(date +"%d/%m/%Y %H:%M:%S")
          
      - name: Checkout Wiki
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki

      - name: Update wiki
        run: |
          #!/bin/sh
          
          git config --global user.email "$GITHUB_ACTOR@$ADDRESS_SUFFIX" 
          git config --global user.name "$GITHUB_ACTOR"
   
          echo \| Date  \| Commentaire \| > tmp.md
          echo \| ------------- \| ------------- \| >>tmp.md
          echo \| $(date +"%d/%m/%Y %H:%M:%S") \| ${{ github.event.head_commit.message }} \| >>tmp.md 
 
          tail -n +2 Home.md >>tmp.md
  
          rm Home.md
          mv tmp.md Home.md

          git add Home.md
          git commit -m "Maj Wiki"
          git push
